# Generated by Django 2.1.7 on 2019-02-27 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('senha', models.CharField(max_length=6)),
                ('nome_de_usuario', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=50, null=True)),
                ('Usuário', models.NullBooleanField(verbose_name='ADM')),
            ],
        ),
    ]
