# Generated by Django 2.1.7 on 2019-02-27 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('territorio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formulario',
            old_name='Usuário',
            new_name='classificacao',
        ),
    ]
