# Generated by Django 2.1.7 on 2019-03-01 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('territorio', '0003_atualizacao_territorio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atualizacao_territorio',
            name='data_de_inicio',
            field=models.DateTimeField(verbose_name='Data de Início'),
        ),
        migrations.AlterField(
            model_name='atualizacao_territorio',
            name='data_de_termino',
            field=models.DateTimeField(verbose_name='Data de Término'),
        ),
    ]
