# Generated by Django 2.1.7 on 2019-03-03 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('territorio', '0004_auto_20190301_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='atualizacao_territorio',
            name='data_ultima_vez_trabalhado',
            field=models.DateTimeField(null=True, verbose_name='Data da última vez trabalhado'),
        ),
    ]
