# Generated by Django 2.1.7 on 2019-03-03 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('territorio', '0005_atualizacao_territorio_data_ultima_vez_trabalhado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atualizacao_territorio',
            name='data_de_inicio',
            field=models.DateField(verbose_name='Data de Início'),
        ),
        migrations.AlterField(
            model_name='atualizacao_territorio',
            name='data_de_termino',
            field=models.DateField(verbose_name='Data de Término'),
        ),
        migrations.AlterField(
            model_name='atualizacao_territorio',
            name='data_ultima_vez_trabalhado',
            field=models.DateField(null=True, verbose_name='Data da última vez trabalhado'),
        ),
    ]
