# Generated by Django 2.1.7 on 2019-03-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('territorio', '0010_auto_20190303_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulario',
            name='classificacao',
        ),
        migrations.AddField(
            model_name='formulario',
            name='user',
            field=models.BooleanField(null=True, verbose_name='ADM'),
        ),
    ]
