# Generated by Django 2.1.7 on 2019-03-29 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('territorio', '0011_auto_20190304_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulario',
            name='user',
        ),
        migrations.AddField(
            model_name='formulario',
            name='tipo_de_usuario',
            field=models.BooleanField(default=False),
        ),
    ]
