# Generated by Django 2.1.7 on 2019-03-29 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('territorio', '0012_auto_20190329_1922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formulario',
            old_name='tipo_de_usuario',
            new_name='ADM',
        ),
    ]
