# Generated by Django 2.1.7 on 2019-04-03 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('territorio', '0014_auto_20190403_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atualizacao_territorio',
            name='data_de_termino',
            field=models.DateTimeField(blank=True, verbose_name='Data de Término'),
        ),
    ]
