# Generated by Django 2.1.7 on 2019-04-03 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('territorio', '0016_auto_20190403_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='atualizacao_territorio',
            name='territorio_finalizado',
            field=models.BooleanField(default=False),
        ),
    ]
